/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dfacedb_DfaceDB */

#ifndef _Included_com_dfacedb_DfaceDB
#define _Included_com_dfacedb_DfaceDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    identify
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dfacedb_DfaceDB_identify
  (JNIEnv *, jobject);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    initLoad
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_initLoad
  (JNIEnv *, jobject);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    uninitLoad
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_uninitLoad
  (JNIEnv *, jobject);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    openDB
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_openDB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    closeDB
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_closeDB
  (JNIEnv *, jobject);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    dbExsitCollection
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_dbExsitCollection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    dbCreateCollection
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_dbCreateCollection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    insertFace
 * Signature: (Ljava/lang/String;Lcom/dfacedb/dto/DBFaceRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_dfacedb_DfaceDB_insertFace
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    fetchFaceById
 * Signature: (Ljava/lang/String;I)Lcom/dfacedb/dto/DBFaceRecord;
 */
JNIEXPORT jobject JNICALL Java_com_dfacedb_DfaceDB_fetchFaceById
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    deleteFaceById
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_deleteFaceById
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    fetchAllFace2Memory
 * Signature: (Ljava/lang/String;Ljava/util/List;)I
 */
JNIEXPORT jobject JNICALL Java_com_dfacedb_DfaceDB_fetchAllFace2Memory
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    totalCollectionRecord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dfacedb_DfaceDB_totalCollectionRecord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dfacedb_DfaceDB_insert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    fetchById
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dfacedb_DfaceDB_fetchById
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    deleteById
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_deleteById
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_dfacedb_DfaceDB
 * Method:    fetchAll
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_dfacedb_DfaceDB_fetchAll
  (JNIEnv *, jobject, jstring, jstring);


JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_updateFace
        (JNIEnv *, jobject, jstring, jobject);


JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_update
        (JNIEnv *, jobject, jstring, jint, jstring);


JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_kvStore
        (JNIEnv *, jobject, jstring, jstring);


JNIEXPORT jstring JNICALL Java_com_dfacedb_DfaceDB_kvFetch
        (JNIEnv *, jobject, jstring);


JNIEXPORT jboolean JNICALL Java_com_dfacedb_DfaceDB_kvDelete
        (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
